#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

AI services (providers are configurable via env vars):
- STT: Whisper (local, free, default) or Cartesia (cloud) [STT_PROVIDER]
- LLM: Ollama (local, free, default) or DeepSeek (cloud) [LLM_PROVIDER]
- TTS: Piper (local, free, default) or Cartesia (cloud) [TTS_PROVIDER]

Run the bot using::

    uv run bot.py
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import DailyRunnerArguments, RunnerArguments, SmallWebRTCRunnerArguments
from pipecat.services.cartesia.stt import CartesiaSTTService
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.deepseek.llm import DeepSeekLLMService
from pipecat.services.ollama.llm import OLLamaLLMService
from pipecat.services.piper.tts import PiperTTSService
from pipecat.services.whisper.stt import WhisperSTTService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.daily.transport import DailyParams, DailyTransport
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.workers.runner import WorkerRunner

load_dotenv(override=True)


def env(name: str, default: str) -> str:
    """Like os.getenv but treats an empty/whitespace value as unset.

    A blank line in .env (e.g. ``OLLAMA_MODEL=``) otherwise overrides the
    default with an empty string, which breaks the service call.
    """
    value = os.getenv(name)
    return value.strip() if value and value.strip() else default


DEFAULT_SYSTEM_PROMPT = (
    "You are a helpful virtual assistant in a real-time voice conversation. "
    "Listen carefully to the user, answer their questions, and reason through "
    "problems step by step before giving a clear, concise answer. "
    "Your responses will be spoken aloud, so avoid emojis, bullet points, code "
    "blocks, or any formatting that can't be read out naturally. Keep replies "
    "brief and conversational."
)

TUTOR_SYSTEM_PROMPT = (
    "You are a warm, patient and encouraging tutor for a young child in Grade 1 "
    "(Year 1 of the British primary curriculum), about five or six years old. "
    "You help with two things: spelling practice and maths practice (counting, "
    "number bonds, simple addition and subtraction, and times tables). "
    "How to behave: "
    "Speak in short, simple, friendly sentences a six-year-old understands. "
    "Your words are spoken aloud, so never use emojis, bullet points or symbols; "
    "say 'plus', 'minus' and 'equals' instead of the signs. "
    "Ask only ONE question at a time, then wait for the child's answer before "
    "continuing. Be very encouraging and praise effort, for example 'Good try!' "
    "or 'Well done!'. If an answer is wrong, stay positive, give a small hint and "
    "let them try again; after a second try, gently tell them the correct answer "
    "and move on. Keep a gentle pace, make it feel like a game, and celebrate "
    "progress often. Use British spelling and vocabulary, for example 'maths' and "
    "'colour'. "
    "For spelling: say the word clearly, use it in a short simple sentence, then "
    "ask the child to spell it out letter by letter and check their answer. "
    "For maths: ask simple questions out loud such as 'What is three plus four?' "
    "and keep the numbers suitable for a six-year-old. "
    "A grown-up may type instructions to you, such as the spelling words for "
    "today or which maths topic to focus on. When they do, use exactly those "
    "words or that topic for the practice session."
)


def build_system_prompt() -> str:
    """Pick the assistant persona. Set ASSISTANT_MODE=tutor for the kids tutor."""
    if env("ASSISTANT_MODE", "assistant").lower() != "tutor":
        return DEFAULT_SYSTEM_PROMPT

    prompt = TUTOR_SYSTEM_PROMPT
    name = env("TUTOR_STUDENT_NAME", "")
    if name:
        prompt += f" The child's name is {name}; use it warmly now and then."
    spelling_words = env("TUTOR_SPELLING_WORDS", "")
    if spelling_words:
        prompt += (
            f" Today's spelling words are: {spelling_words}. Use these words for spelling practice."
        )
    maths_focus = env("TUTOR_MATHS_FOCUS", "")
    if maths_focus:
        prompt += f" For maths today, focus on: {maths_focus}."
    return prompt


def build_intro_message() -> str:
    """The first thing the assistant says when the client connects."""
    if env("ASSISTANT_MODE", "assistant").lower() == "tutor":
        name = env("TUTOR_STUDENT_NAME", "")
        greet = f" Greet {name} by name." if name else ""
        return (
            "Greet the child cheerfully in one or two short sentences and ask "
            "whether they would like to practise spelling or maths today." + greet
        )
    return "Start by concisely introducing yourself."


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service - local Whisper by default (free, no quota), or Cartesia.
    stt_provider = env("STT_PROVIDER", "whisper").lower()
    if stt_provider == "cartesia":
        stt = CartesiaSTTService(api_key=os.getenv("CARTESIA_API_KEY"))
    else:
        # Whisper runs locally in-process; the model is downloaded on first use
        # (pre-baked in the Docker image). "base" is a good CPU speed/quality balance.
        stt = WhisperSTTService(
            settings=WhisperSTTService.Settings(model=env("WHISPER_MODEL", "base")),
        )
    logger.info(f"Using STT provider: {stt_provider}")

    # Text-to-Speech service - local Piper by default (free, no quota), or Cartesia.
    tts_provider = env("TTS_PROVIDER", "piper").lower()
    if tts_provider == "cartesia":
        tts = CartesiaTTSService(
            api_key=os.getenv("CARTESIA_API_KEY"),
            settings=CartesiaTTSService.Settings(
                voice=env("CARTESIA_VOICE_ID", "71a7ad14-091c-4e8e-a314-022ece01c121"),
            ),
        )
    else:
        # Piper runs locally in-process; the voice model is downloaded into
        # PIPER_DOWNLOAD_DIR on first use (pre-baked in the Docker image).
        tts = PiperTTSService(
            download_dir=Path(env("PIPER_DOWNLOAD_DIR", str(Path.cwd() / "piper_voices"))),
            settings=PiperTTSService.Settings(
                voice=env("PIPER_VOICE", "en_US-amy-medium"),
            ),
        )
    logger.info(f"Using TTS provider: {tts_provider}")

    # LLM service - local Ollama by default (free, no API key), or DeepSeek.
    provider = env("LLM_PROVIDER", "ollama").lower()
    if provider == "deepseek":
        llm = DeepSeekLLMService(
            api_key=os.getenv("DEEPSEEK_API_KEY"),
            settings=DeepSeekLLMService.Settings(
                model=env("DEEPSEEK_MODEL", "deepseek-chat"),
            ),
        )
    else:
        llm = OLLamaLLMService(
            base_url=env("OLLAMA_BASE_URL", "http://127.0.0.1:11434/v1"),
            settings=OLLamaLLMService.Settings(
                model=env("OLLAMA_MODEL", "qwen2.5:1.5b"),
            ),
        )
    logger.info(f"Using LLM provider: {provider}")

    context = LLMContext(messages=[{"role": "system", "content": build_system_prompt()}])
    logger.info(f"Assistant mode: {env('ASSISTANT_MODE', 'assistant')}")
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
        ),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message({"role": "developer", "content": build_intro_message()})
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case DailyRunnerArguments():
            transport = DailyTransport(
                runner_args.room_url,
                runner_args.token,
                "Pipecat Bot",
                params=DailyParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pathlib import Path

    from fastapi.staticfiles import StaticFiles
    from pipecat.runner.run import app, main

    # Serve the custom 3D-avatar web client at /avatar (same origin as /api/offer).
    client_dir = Path(__file__).parent / "client"
    if client_dir.is_dir():
        app.mount("/avatar", StaticFiles(directory=str(client_dir), html=True), name="avatar")

    main()
