#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

AI services (providers are configurable via env vars):
- Cartesia (Speech-to-Text)
- LLM: Ollama (local, free, default) or DeepSeek (cloud) [LLM_PROVIDER]
- TTS: Piper (local, free, default) or Cartesia (cloud) [TTS_PROVIDER]

Run the bot using::

    uv run bot.py
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import DailyRunnerArguments, RunnerArguments, SmallWebRTCRunnerArguments
from pipecat.services.cartesia.stt import CartesiaSTTService
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.deepseek.llm import DeepSeekLLMService
from pipecat.services.ollama.llm import OLLamaLLMService
from pipecat.services.piper.tts import PiperTTSService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.daily.transport import DailyParams, DailyTransport
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.workers.runner import WorkerRunner

load_dotenv(override=True)


def env(name: str, default: str) -> str:
    """Like os.getenv but treats an empty/whitespace value as unset.

    A blank line in .env (e.g. ``OLLAMA_MODEL=``) otherwise overrides the
    default with an empty string, which breaks the service call.
    """
    value = os.getenv(name)
    return value.strip() if value and value.strip() else default


SYSTEM_PROMPT = (
    "You are a helpful virtual assistant in a real-time voice conversation. "
    "Listen carefully to the user, answer their questions, and reason through "
    "problems step by step before giving a clear, concise answer. "
    "Your responses will be spoken aloud, so avoid emojis, bullet points, code "
    "blocks, or any formatting that can't be read out naturally. Keep replies "
    "brief and conversational."
)


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service (Cartesia)
    stt = CartesiaSTTService(api_key=os.getenv("CARTESIA_API_KEY"))

    # Text-to-Speech service - local Piper by default (free, no quota), or Cartesia.
    tts_provider = env("TTS_PROVIDER", "piper").lower()
    if tts_provider == "cartesia":
        tts = CartesiaTTSService(
            api_key=os.getenv("CARTESIA_API_KEY"),
            settings=CartesiaTTSService.Settings(
                voice=env("CARTESIA_VOICE_ID", "71a7ad14-091c-4e8e-a314-022ece01c121"),
            ),
        )
    else:
        # Piper runs locally in-process; the voice model is downloaded into
        # PIPER_DOWNLOAD_DIR on first use (pre-baked in the Docker image).
        tts = PiperTTSService(
            download_dir=Path(env("PIPER_DOWNLOAD_DIR", str(Path.cwd() / "piper_voices"))),
            settings=PiperTTSService.Settings(
                voice=env("PIPER_VOICE", "en_US-amy-medium"),
            ),
        )
    logger.info(f"Using TTS provider: {tts_provider}")

    # LLM service - local Ollama by default (free, no API key), or DeepSeek.
    provider = env("LLM_PROVIDER", "ollama").lower()
    if provider == "deepseek":
        llm = DeepSeekLLMService(
            api_key=os.getenv("DEEPSEEK_API_KEY"),
            settings=DeepSeekLLMService.Settings(
                model=env("DEEPSEEK_MODEL", "deepseek-chat"),
            ),
        )
    else:
        llm = OLLamaLLMService(
            base_url=env("OLLAMA_BASE_URL", "http://127.0.0.1:11434/v1"),
            settings=OLLamaLLMService.Settings(
                model=env("OLLAMA_MODEL", "qwen2.5:1.5b"),
            ),
        )
    logger.info(f"Using LLM provider: {provider}")

    context = LLMContext(messages=[{"role": "system", "content": SYSTEM_PROMPT}])
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
        ),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message(
            {"role": "developer", "content": "Start by concisely introducing yourself."}
        )
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case DailyRunnerArguments():
            transport = DailyTransport(
                runner_args.room_url,
                runner_args.token,
                "Pipecat Bot",
                params=DailyParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pathlib import Path

    from fastapi.staticfiles import StaticFiles
    from pipecat.runner.run import app, main

    # Serve the custom 3D-avatar web client at /avatar (same origin as /api/offer).
    client_dir = Path(__file__).parent / "client"
    if client_dir.is_dir():
        app.mount("/avatar", StaticFiles(directory=str(client_dir), html=True), name="avatar")

    main()
